CREATE DATABASE person_database;

\c person_database;

CREATE TABLE IF NOT EXISTS "user"(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(30),
    password BYTEA
);

CREATE TABLE IF NOT EXISTS person(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30),
    phone VARCHAR(14),
    email  VARCHAR(30)
);

